
{ pkgs, lib, config, secrets, ... }:

{


  # Containers
  virtualisation.oci-containers.containers."www-domain1" = {
    image = "ghcr.io/suddenlybanana/www.${secrets.zones.float-play.domain1.name}:main";
    ports = [
      "8080:80/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=website"
      "--network=www-domain1_default"
    ];
  };
  systemd.services."podman-www-domain1" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-www-domain1_default.service"
    ];
    requires = [
      "podman-network-www-domain1_default.service"
    ];
    partOf = [
      "podman-compose-www-domain1-root.target"
    ];
    wantedBy = [
      "podman-compose-www-domain1-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-www-domain1_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f www-domain1_default";
    };
    script = ''
      podman network inspect www-domain1_default || podman network create www-domain1_default
    '';
    partOf = [ "podman-compose-www-domain1-root.target" ];
    wantedBy = [ "podman-compose-www-domain1-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-www-domain1-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
